import type { Lang } from "./I18n";

// Conteúdo da landing em 3 idiomas. A página lê pick(LANDING, lang).
export interface LandingContent {
  nav: { id: string; label: string }[];
  hero: { badge: string; titleA: string; titleB: string; rotate: string[]; subtitle: string; ctaPrimary: string; ctaSecondary: string; micro: string[]; live: { title: string; health: string; risk: string; cur: string; feed: string[]; rows: string[] } };
  metrics: [string, string][];
  feitoPara: string;
  personas: [string, string, string][];
  coverage: { badge: string; title: string; sub: string; items: [string, string, string][] };
  produto: { badge: string; title: string; sub: string; dash: string; cockpit: string; impact: string; impactNow: string; impactRows: [string, string][]; note: string; tryTitle: string; trySub: string; healthAvg: string; cockpitApproval: string; impactTotal: string };
  demo: { fail: string; btn: string; btnRunning: string; hint: string; script: string[] };
  roi: { badge: string; title: string; sub: string; hoursLabel: string; costLabel: string; assume: string; loseNow: string; saved: string; perMonth: string; perYear: string; cta: string };
  problema: { title: string; p: string; cards: [string, string][]; beforeTag: string; beforeText: string; beforeChips: string[]; afterTag: string; afterText: string; afterChips: string[]; drag: string };
  como: { title: string; sub: string; flow: [string, string, string][]; steps: [string, string, string][] };
  plataforma: { title: string; sub: string };
  groups: { accent: string; title: string; feats: { key: string; icon: string; name: string; tagline: string }[] }[];
  featHover: string;
  s4: { badge: string; titlePre: string; sub: string; cards: { icon: string; title: string; desc: string }[] };
  innovHead: { badge: string; title: string; sub: string; hover: string; more: string };
  innovations: { key: string; icon: string; name: string; tagline: string; desc: string; benefit: string }[];
  comparativo: { title: string; sub: string; cols: string[]; rows: [string, string, string, string, string][]; legend: string };
  trust: { title: string; band: [string, string][]; cards: [string, string][]; roadmap: string };
  planos: { title: string; sub1: string; sub2: string; monthly: string; annual: string; annualBadge: string; perYear: string; perMonthEq: string; cta: string };
  faq: { title: string; items: [string, string][] };
  lead: { tag: string; title: string; sub: string; placeholder: string; btn: string; btnSending: string; doneMsg: string; download: string };
  ctaFinal: { title: string; sub: string; btn: string };
  footer: { tagline: string; terms: string; privacy: string; contract: string; contact: string; login: string };
  interest: { title: string; sub: string; name: string; email: string; phone: string; company: string; role: string; message: string; send: string; sending: string; okTitle: string; okMsg: string; close: string; err: string };
}

const COVERAGE_BASE: [string, string][] = [
  ["☁️", "S/4HANA Cloud"], ["🗄️", "ECC / S/4 on-prem"], ["🔀", "CPI / Cloud Integration"], ["🧩", "AIF"],
  ["📨", "Event Mesh"], ["🛒", "Ariba"], ["👥", "SuccessFactors"], ["✈️", "Concur"], ["🧰", "Fieldglass"],
  ["🎧", "CX (Sales/Service)"], ["🛍️", "Commerce"], ["🔗", "API Management"], ["🪐", "BTP Cockpit"],
  ["🔁", "PI/PO"], ["🩺", "Basis & HANA"], ["📑", "B2B / EDI (TPM)"], ["🧾", "Fiscal BR"], ["🚚", "Transports (STMS)"],
];
const cov = (subs: string[]): [string, string, string][] => COVERAGE_BASE.map((c, i) => [c[0], c[1], subs[i]]);

const COV_SUB_PT = ["Upgrade, Clean Core, APIs", "via Agente (RFC/IDoc)", "Message Processing Logs", "Application Interface Framework", "dead-letter, lag", "suppliers, reporting", "User, EmpJob", "despesas, relatórios", "força de trabalho externa", "C4C OData", "OCC API", "proxies publicados", "keys, destinations, quotas", "channels, backlog", "jobs, dumps, locks, memória", "parceiros e acordos", "NF-e, CT-e, SPED, eSocial", "blast radius"];
const COV_SUB_EN = ["Upgrade, Clean Core, APIs", "via Agent (RFC/IDoc)", "Message Processing Logs", "Application Interface Framework", "dead-letter, lag", "suppliers, reporting", "User, EmpJob", "expenses, reports", "external workforce", "C4C OData", "OCC API", "published proxies", "keys, destinations, quotas", "channels, backlog", "jobs, dumps, locks, memory", "partners & agreements", "e-invoice, tax (BR)", "blast radius"];
const COV_SUB_ES = ["Upgrade, Clean Core, APIs", "vía Agente (RFC/IDoc)", "Message Processing Logs", "Application Interface Framework", "dead-letter, lag", "suppliers, reporting", "User, EmpJob", "gastos, informes", "fuerza de trabajo externa", "C4C OData", "OCC API", "proxies publicados", "keys, destinations, quotas", "channels, backlog", "jobs, dumps, locks, memoria", "socios y acuerdos", "factura electrónica, fiscal (BR)", "blast radius"];

export const LANDING: Record<Lang, LandingContent> = {
  pt: {
    nav: [{ id: "problema", label: "Problema" }, { id: "cobertura", label: "Cobertura" }, { id: "produto", label: "Por dentro" }, { id: "roi", label: "ROI" }, { id: "comparativo", label: "Comparativo" }, { id: "planos", label: "Planos" }, { id: "faq", label: "FAQ" }],
    hero: { badge: "18+ produtos SAP · IA de ponta a ponta · white-label", titleA: "Inove a operação", titleB: "da sua consultoria", rotate: ["S/4HANA Cloud", "Ariba & SF", "CPI & AIF", "BTP", "fiscal BR", "todo o SAP"], subtitle: "Um só painel que monitora, prevê, corrige e prova valor em R$ em todo o landscape SAP do cliente — do IDoc clássico ao S/4HANA Cloud, Ariba, SuccessFactors, BTP e fiscal brasileiro.", ctaPrimary: "Quero inovar minha operação →", ctaSecondary: "Ver tudo que cobrimos", micro: ["✓ Sem abrir portas no cliente", "✓ Multi-cliente", "✓ Pronto em dias, não meses"], live: { title: "SAPLINK · carteira ao vivo", health: "Saúde da carteira", risk: "Em risco agora", cur: "R$", feed: ["IA corrigiu 3 IDocs travados · sem intervenção", "Alerta CRITICAL em CPI · diagnóstico em 4s", "NF-e rejeitada reprocessada · SEFAZ OK", "Fila qRFC destravada · 0 pendências", "Runbook aplicado · 'Sold-to not found'"], rows: ["S/4HANA Cloud · OData", "CPI · Pedidos B2B", "IDoc · INVOIC02", "RFC · PI_PROD", "Event Mesh · BP"] } },
    metrics: [["18+", "produtos SAP cobertos"], ["20+", "capacidades na plataforma"], ["13", "diferenciais que ninguém tem"], ["0", "portas abertas no cliente"]],
    feitoPara: "Feito para",
    personas: [["🏢", "Consultorias SAP", "Monitore a carteira inteira de clientes num painel, com sua marca."], ["🛠️", "Times de AMS / Sustentação", "Menos apagar incêndio: detecção, diagnóstico e remediação com aprovação."], ["🤝", "Parceiros & Integradores", "Prove valor em R$ ao cliente e aumente retenção e receita recorrente."]],
    coverage: { badge: "COBERTURA TOTAL", title: "Todo o universo SAP do seu cliente. Numa tela.", sub: "Integração clássica, nuvem, LoB, plataforma, Basis e fiscal brasileiro — o concorrente cobre um pedaço; o SAPLINK cobre o conjunto.", items: cov(COV_SUB_PT) },
    produto: { badge: "POR DENTRO", title: "Veja o SAPLINK por dentro", sub: "Painéis reais do produto — saúde da carteira, cockpit operacional e o impacto em R$.", dash: "📊 Dashboard · saúde da carteira", cockpit: "🛰️ Cockpit · IDocs & filas", impact: "💸 Impacto em R$ · ao vivo", impactNow: "Dinheiro parado agora", impactRows: [["Faturamento (NF-e parada)", "R$ 52,0k"], ["Pedidos travados (CPI)", "R$ 24,7k"], ["Fiscal em risco (DRC)", "R$ 12,5k"]], note: "Telas representativas da interface do produto.", tryTitle: "Experimente a IA agora — sem cadastro", trySub: "Uma falha de CPI de exemplo. Clique e veja o diagnóstico + correção.", healthAvg: "health médio", cockpitApproval: "✓ Remediação com aprovação · trava de produção", impactTotal: "R$ 89,2k" },
    demo: { fail: "❌ CPI · Pedidos B2B — FALHA", btn: "🤖 Diagnosticar", btnRunning: "Diagnosticando…", hint: "Clique em “Diagnosticar” e veja a IA achar a causa raiz e a correção — sem cadastro.", script: ["🔎 Lendo o Message Processing Log do iFlow ‘Pedidos B2B’…", "⚠️ Causa raiz: Sold-to party 0001234 não existe no S/4HANA.", "🛠️ Correção: criar/checar o BP (XD01/BP) e reprocessar a mensagem.", "📋 SAP Note provável: 2900000 — Sales Order replication error.", "✅ Correção pronta pra aplicar (com aprovação · trava de produção)."] },
    roi: { badge: "CALCULADORA", title: "Quanto a integração parada custa pra você?", sub: "Ajuste com os seus números e veja a economia estimada — a linguagem que o CFO entende.", hoursLabel: "Horas de parada não planejada / mês (carteira)", costLabel: "Custo médio de parada por hora", assume: "Estimativa: detecção e remediação rápidas reduzem até 70% do tempo de parada. Ajuste com os seus números.", loseNow: "Você perde hoje, por mês", saved: "Economia estimada com o SAPLINK", perMonth: "/mês", perYear: "/ano", cta: "Quero recuperar esse valor →" },
    problema: { title: "O reativo custa cliente e margem", p: "Integração SAP quebra em silêncio e o cliente descobre antes de você. O time vive apagando incêndio, sem visão única, e fica difícil provar o valor entregue. O SAPLINK inverte o jogo.", cards: [["Antes", "IDoc travado, RFC caída, NF-e parada — descoberto tarde demais."], ["Sem o SAPLINK", "Planilha, transação por transação, cliente por cliente. Não escala."], ["Com o SAPLINK", "Radar único, alertas, IA e prova de valor em R$. Você no controle."]], beforeTag: "ANTES · reativo", beforeText: "Planilha, transação por transação, cliente por cliente. IDoc travado descoberto tarde. Cliente liga antes de você ver.", beforeChips: ["sem visão única", "apaga incêndio", "valor invisível"], afterTag: "DEPOIS · com SAPLINK", afterText: "Radar único da carteira · alertas priorizados · IA diagnostica e corrige · R$ em risco ao vivo · SLA por cliente.", afterChips: ["health 92", "0 portas abertas", "−70% downtime", "prova em R$"], drag: "← arraste para comparar →" },
    como: { title: "Como funciona", sub: "Do SAP do cliente à ação — o dado flui só de saída, sem abrir portas.", flow: [["🗄️", "SAP do cliente", "S/4 · ECC · CPI"], ["🔌", "Agente / Conector", "saída-only · OData"], ["◆", "SAPLINK", "IA · multi-cliente"], ["✅", "Ação & valor", "alerta · correção · R$"]], steps: [["1", "Conecte", "Agente Docker (RFC/IDoc) só com saída HTTPS, ou Communication Arrangement no S/4HANA Cloud. Zero porta aberta."], ["2", "Enxergue", "Saúde de todas as integrações de todos os clientes num painel multi-cliente, em tempo real."], ["3", "Antecipe & corrija", "IA diagnostica, prevê falhas e remedia (com aprovação) — IDoc, fila, RFC, fiscal."], ["4", "Prove valor", "SLA por cliente, impacto em R$ e portal white-label. Você vira o radar do SAP do cliente."]] },
    plataforma: { title: "Uma plataforma, tudo que a operação SAP precisa", sub: "Mais de 20 capacidades — do cockpit clássico à IA e ao S/4HANA Cloud." },
    groups: [
      { accent: "#22d3ee", title: "Operação", feats: [
        { key: "Cockpit de IDoc & filas", icon: "🛰️", name: "Cockpit de IDoc & filas", tagline: "BD87 + SMQ + SM58 num painel multi-cliente" },
        { key: "Remediação autônoma", icon: "✨", name: "Remediação autônoma", tagline: "Reprocessa/destrava com aprovação e log" },
        { key: "Catálogo de interfaces", icon: "📚", name: "Catálogo de interfaces", tagline: "Landscape auto-descoberto (WE20/SM59)" },
        { key: "Alertas em tempo real", icon: "🔔", name: "Alertas em tempo real", tagline: "Detecção e resolução automática" } ] },
      { accent: "#a78bfa", title: "Inteligência IA", feats: [
        { key: "Copiloto da carteira", icon: "💬", name: "Copiloto da carteira", tagline: "Pergunte em linguagem natural" },
        { key: "Diagnóstico + SAP Notes", icon: "🤖", name: "Diagnóstico + SAP Notes", tagline: "Causa raiz e a Nota provável" },
        { key: "Previsão de falha", icon: "🔮", name: "Previsão de falha", tagline: "Anomalia antes de quebrar" },
        { key: "Digest semanal por IA", icon: "📬", name: "Digest semanal por IA", tagline: "Resumo white-label no e-mail" } ] },
      { accent: "#34d399", title: "Valor & SLA", feats: [
        { key: "SLA por cliente", icon: "📈", name: "SLA por cliente", tagline: "Compliance + relatório por IA" },
        { key: "Impacto em R$", icon: "💰", name: "Impacto em R$", tagline: "Custo da parada por hora" },
        { key: "Benchmark de mercado", icon: "🏆", name: "Benchmark de mercado", tagline: "Sua carteira vs percentil" },
        { key: "Portal do cliente", icon: "🪪", name: "Portal do cliente", tagline: "White-label, read-only" } ] },
      { accent: "#fbbf24", title: "S/4HANA Cloud", feats: [
        { key: "Radar de Upgrade", icon: "🚀", name: "Radar de Upgrade", tagline: "O que quebra no próximo release" },
        { key: "Clean Core Score", icon: "🧼", name: "Clean Core Score", tagline: "A métrica que a SAP cobra" },
        { key: "Fiscal DRC (NF-e)", icon: "🧾", name: "Fiscal DRC (NF-e)", tagline: "Rejeição SEFAZ, contingência" },
        { key: "Event Mesh + CPI/AIF", icon: "📨", name: "Event Mesh + CPI/AIF", tagline: "Dead-letter, lag, MPL" } ] },
      { accent: "#f87171", title: "Resposta & Confiança", feats: [
        { key: "On-call multicanal", icon: "📣", name: "On-call multicanal", tagline: "Slack/Teams/Webhook/e-mail + escalonamento" },
        { key: "Tickets Jira/ServiceNow", icon: "🎫", name: "Tickets Jira/ServiceNow", tagline: "Alerta vira chamado e fecha sozinho" },
        { key: "Radar de validade", icon: "📡", name: "Radar de validade", tagline: "Certificados e segredos vencendo" },
        { key: "Transports (STMS)", icon: "🚚", name: "Transports (STMS)", tagline: "Correlaciona incidente x transporte" } ] },
    ],
    featHover: "Ver detalhes, simulador e como implementar →",
    s4: { badge: "CARRO-CHEFE", titlePre: "Pronto para o", sub: "A edição que a SAP empurra em todo mundo — sem GUI, upgrade forçado 2×/ano e API-first. O SAPLINK cobre exatamente o que falta, conectando por Communication Arrangement (OAuth), sem instalar nada.", cards: [
      { icon: "🚀", title: "Radar de Upgrade", desc: "O que vai quebrar no próximo release — mapeado ao que você usa." },
      { icon: "🧼", title: "Clean Core Score", desc: "A métrica que a própria SAP cobra, com plano de remediação." },
      { icon: "🧾", title: "Fiscal DRC", desc: "NF-e/SEFAZ: rejeição, contingência e reprocesso. Mata o mercado BR." },
      { icon: "📨", title: "Event Mesh + CPI/AIF", desc: "Dead-letter, lag e Message Processing Logs reais." } ] },
    innovHead: { badge: "🦄 EXCLUSIVO · NO AR", title: "O que não existe em nenhum outro sistema", sub: "Treze diferenciais que viram moat: efeito de rede, dado cross-camada que só nós temos, autonomia, reconciliação, IA que escreve a correção, operação por WhatsApp, pré-voo de mudança, time machine, auditoria, FinOps e a linguagem do CFO. Clique pra explorar com simulador.", hover: "Abrir detalhes + simulador →", more: "Ver todas as funcionalidades em detalhe, com exemplos e ganhos →" },
    innovations: [
      { key: "Rede Federada de Falhas", icon: "🛰️", name: "Rede Federada de Falhas", tagline: "O \"Waze do SAP\"", desc: "Cada falha e a correção que funcionou viram conhecimento anônimo da rede. Quando algo quebra no seu cliente, o SAPLINK já sabe a correção vencedora — porque viu acontecer em dezenas de outros ambientes.", benefit: "Fica mais inteligente a cada cliente (efeito de rede)." },
      { key: "Causa raiz cross-camada", icon: "🔗", name: "Causa raiz cross-camada", tagline: "On-prem + nuvem juntos", desc: "Cruza os transports (STMS) com as falhas de CPI/IDoc que vieram depois e aponta a mudança que provavelmente causou. Ninguém mais tem as duas camadas no mesmo lugar.", benefit: "Achar a causa em minutos, não em horas." },
      { key: "AMS Autônomo", icon: "🤖", name: "AMS Autônomo", tagline: "Self-healing que aprende", desc: "Detecta → diagnostica → corrige → mede → aprende. Correções de alta confiança são aplicadas sozinhas (com rollback e rastro). A confiança vem da Rede Federada.", benefit: "Reduz o L1/L2 manual a quase zero." },
      { key: "Dinheiro em risco (ao vivo)", icon: "💸", name: "Dinheiro em risco (ao vivo)", tagline: "Linguagem de CFO", desc: "Traduz cada falha técnica em R$ parados agora — custo de parada por hora + documentos fiscais bloqueados, por processo de negócio.", benefit: "Muda a conversa de venda de técnica para financeira." },
      { key: "Reconciliação ponta-a-ponta", icon: "🔁", name: "Reconciliação ponta-a-ponta", tagline: "Entregue ≠ virou negócio", desc: "Rastreia o documento pela jornada (pedido → ordem → fatura) e mostra onde o volume se perde. Pega a falha silenciosa que diz \"sucesso\" mas o objeto nunca nasceu.", benefit: "Acha o vazamento que nenhum monitor vê." },
      { key: "Remediação generativa", icon: "⚙️", name: "Remediação generativa", tagline: "A IA escreve a correção", desc: "Não só descreve o problema — entrega o artefato pronto (Groovy, mapeamento, filtro OData) para colar e aplicar.", benefit: "De \"explica\" para \"resolve\" em segundos." },
      { key: "ChatOps por WhatsApp", icon: "💬", name: "ChatOps por WhatsApp", tagline: "Opere o SAP por mensagem", desc: "\"Reprocessa os IDocs do cliente X\" pelo WhatsApp/Telegram — a IA entende, age e pede aprovação para o que mexe no SAP.", benefit: "Operação na palma da mão, sem abrir o painel." },
      { key: "Perda silenciosa de negócio", icon: "📉", name: "Perda silenciosa de negócio", tagline: "Radar de receita", desc: "Alerta quando o volume cai muito abaixo do normal — mesmo com tudo verde tecnicamente. Captura a receita parando antes de virar reclamação.", benefit: "Vê o prejuízo que o monitor técnico não vê." },
      { key: "Pré-voo de mudança", icon: "🧨", name: "Pré-voo de mudança", tagline: "Blast radius antes do deploy", desc: "Antes do transport ir pra PRD, mostra o raio de impacto (interfaces, processos, R$) e o score de risco — com plano de teste.", benefit: "Acaba com a surpresa pós-upgrade." },
      { key: "Time machine de incidente", icon: "⏪", name: "Time machine de incidente", tagline: "Replay + 'e se?'", desc: "Reconstrói a linha do tempo do incidente e mostra quanto seria economizado com detecção mais rápida.", benefit: "Prova de ROI irrefutável." },
      { key: "Auditoria & Compliance", icon: "🛡️", name: "Auditoria & Compliance", tagline: "SoD automático", desc: "Trilha de mudanças e remediações + checagem de segregação de função, com evidências prontas pro auditor.", benefit: "Compliance sem montar planilha." },
      { key: "Parceiros EDI", icon: "🤝", name: "Parceiros EDI", tagline: "Quem manda dado ruim", desc: "Ranqueia parceiros por frequência de erro — pra cobrar o fornecedor certo, não a sua TI.", benefit: "Munição pra cobrar o parceiro." },
      { key: "FinOps de BTP", icon: "💵", name: "FinOps de BTP", tagline: "Custo de nuvem por IFlow", desc: "Liga volume ao consumo do BTP e flagra o IFlow desgovernado queimando crédito.", benefit: "Fim da surpresa na fatura do BTP." },
    ],
    comparativo: { title: "Por que SAPLINK e não o resto", sub: "O concorrente cobre um pedaço. O SAPLINK cobre o conjunto — com IA e prova de valor.", cols: ["Planilha / manual", "Monitor genérico", "SAP Focused Run", "SAPLINK"], rows: [["Multi-cliente num painel", "✗", "~", "~", "✓"], ["IDoc/RFC + CPI + S/4HANA Cloud juntos", "✗", "~", "~", "✓"], ["IA: diagnóstico + correção pronta", "✗", "✗", "~", "✓"], ["Remediação com aprovação + trava de PRD", "✗", "✗", "~", "✓"], ["Prova de valor em R$ / SLA por cliente", "~", "✗", "~", "✓"], ["Fiscal BR (NF-e, CT-e, SPED, eSocial)", "✗", "✗", "✗", "✓"], ["Sem abrir portas / sem S-user", "✓", "~", "✗", "✓"], ["White-label + portal do cliente", "✗", "✗", "✗", "✓"], ["Pronto em dias", "✓", "~", "✗", "✓"]], legend: "✓ tem · ~ parcial · ✗ não tem" },
    trust: { title: "Seguro para o ambiente do seu cliente", band: [["🔒", "Sem abrir portas no cliente"], ["🪪", "Sem S-user · sem add-on"], ["🔑", "Credenciais cifradas (AES)"], ["🧱", "Isolamento multi-tenant"], ["✋", "Ação no SAP só com aprovação"], ["🌎", "Conformidade LGPD"], ["🟢", "Trava de produção (PRD)"], ["🧪", "Ambientes DEV/HML/PRD"]], cards: [["🇧🇷 Dados no Brasil", "Hospedagem e dados sob LGPD; você é o controlador, o SAPLINK é operador."], ["🔐 Acesso mínimo", "Conexão por APIs liberadas / Communication Arrangement. Sem S-user, sem add-on, sem porta de entrada."], ["✋ Mudança no SAP só com aval", "Toda remediação é aprovar→executar→log. Em produção, confirmação extra (trava de PRD)."]], roadmap: "Certificações SOC 2 / ISO 27001 no roadmap." },
    planos: { title: "Planos", sub1: "Add-ons de integração e usuário extra. Cobrança automática ou avulsa.", sub2: "🎁 1ª mensalidade grátis nos planos Business e Enterprise · Pro com 50% OFF no 1º mês · fidelidade mínima de 3 meses.", monthly: "Mensal", annual: "Anual", annualBadge: "2 meses grátis", perYear: "/ano", perMonthEq: "/mês · 2 meses grátis", cta: "Tenho interesse" },
    faq: { title: "Perguntas frequentes", items: [["Preciso abrir portas no SAP do cliente?", "Não. OData/REST é monitorado direto; RFC/IDoc usa o Agente Docker com tráfego só de saída. No S/4HANA Cloud, conecta por Communication Arrangement (OAuth) — nada instalado no cliente."], ["Funciona com S/4HANA Cloud?", "Sim — é o nosso carro-chefe: Radar de Upgrade, Clean Core Score, Fiscal DRC, Event Mesh e CPI/AIF, via APIs liberadas."], ["Os dados ficam seguros?", "Credenciais cifradas em repouso, isolamento multi-tenant por consultoria, e nenhuma ação no SAP roda sem aprovação humana (com log)."], ["É white-label?", "Sim. Logo e cor da sua consultoria na interface, nos relatórios e no portal do cliente final."], ["Separa DEV, homologação e produção?", "Sim. Cada integração tem ambiente (DEV/HML/PRD); dados, conexões, métricas e faturamento ficam isolados. Em produção há trava extra: remediação e auto-heal exigem aprovação humana."], ["Quanto tempo pra implantar?", "Dias, não meses. Conecta por Communication Arrangement (nuvem) ou o Agente Docker (on-prem) e os dados começam a aparecer no painel."], ["E a LGPD?", "Conformidade LGPD: dados cifrados, isolamento por consultoria, e Termos + Política publicados. Você é o controlador; o SAPLINK é operador."], ["Tem fidelidade?", "Permanência mínima de 3 meses. 1ª mensalidade grátis nos planos Business/Enterprise e 50% OFF no 1º mês do Pro."], ["Como vende para a minha consultoria?", "Como serviço mensal de monitoramento e governança por cliente — receita recorrente, retenção e prova de valor em R$."]] },
    lead: { tag: "Material gratuito", title: "Deck de vendas do SAPLINK (PDF)", sub: "A visão completa pra apresentar internamente ou ao cliente: o que monitora, como gera receita recorrente e prova de valor em R$.", placeholder: "seu@email.com", btn: "Receber o material", btnSending: "Liberando…", doneMsg: "✓ Pronto! Seu material está liberado.", download: "⬇ Baixar o deck (PDF)" },
    ctaFinal: { title: "Pare de apagar incêndio. Comece a operar.", sub: "Deixe seu contato — o time de vendas mostra o SAPLINK no SAP dos seus clientes.", btn: "Tenho interesse →" },
    footer: { tagline: "Operação de integrações SAP", terms: "Termos", privacy: "Privacidade", contract: "Contrato/SLA", contact: "Contato", login: "Entrar" },
    interest: { title: "Tenho interesse", sub: "Deixe seus dados e o time de vendas fala com você.", name: "Nome *", email: "E-mail *", phone: "Telefone / WhatsApp", company: "Empresa / Consultoria", role: "Seu cargo", message: "O que você procura? (opcional)", send: "Enviar", sending: "Enviando…", okTitle: "Recebemos seu interesse!", okMsg: "Nosso time entra em contato em breve. Obrigado!", close: "Fechar", err: "Não foi possível enviar. Tente de novo." },
  },
  en: {
    nav: [{ id: "problema", label: "Problem" }, { id: "cobertura", label: "Coverage" }, { id: "produto", label: "Inside" }, { id: "roi", label: "ROI" }, { id: "comparativo", label: "Compare" }, { id: "planos", label: "Pricing" }, { id: "faq", label: "FAQ" }],
    hero: { badge: "18+ SAP products · end-to-end AI · white-label", titleA: "Modernize the operations", titleB: "of your consultancy", rotate: ["S/4HANA Cloud", "Ariba & SF", "CPI & AIF", "BTP", "BR tax", "all of SAP"], subtitle: "One dashboard that monitors, predicts, fixes and proves value in $ across the client's entire SAP landscape — from classic IDoc to S/4HANA Cloud, Ariba, SuccessFactors, BTP and Brazilian tax.", ctaPrimary: "Modernize my operation →", ctaSecondary: "See everything we cover", micro: ["✓ No inbound ports on the client", "✓ Multi-client", "✓ Live in days, not months"], live: { title: "SAPLINK · portfolio live", health: "Portfolio health", risk: "At risk now", cur: "$", feed: ["AI fixed 3 stuck IDocs · no intervention", "CRITICAL CPI alert · diagnosed in 4s", "Rejected e-invoice reprocessed · OK", "qRFC queue unblocked · 0 pending", "Runbook applied · 'Sold-to not found'"], rows: ["S/4HANA Cloud · OData", "CPI · B2B Orders", "IDoc · INVOIC02", "RFC · PI_PROD", "Event Mesh · BP"] } },
    metrics: [["18+", "SAP products covered"], ["20+", "platform capabilities"], ["13", "differentiators nobody else has"], ["0", "inbound ports on the client"]],
    feitoPara: "Built for",
    personas: [["🏢", "SAP consultancies", "Monitor your whole client portfolio in one dashboard, under your brand."], ["🛠️", "AMS / Support teams", "Less firefighting: detection, diagnosis and remediation with approval."], ["🤝", "Partners & Integrators", "Prove value in $ to the client and grow retention and recurring revenue."]],
    coverage: { badge: "FULL COVERAGE", title: "Your client's entire SAP universe. On one screen.", sub: "Classic integration, cloud, LoB, platform, Basis and Brazilian tax — competitors cover a slice; SAPLINK covers the whole.", items: cov(COV_SUB_EN) },
    produto: { badge: "INSIDE", title: "See SAPLINK from the inside", sub: "Real product panels — portfolio health, operational cockpit and the impact in $.", dash: "📊 Dashboard · portfolio health", cockpit: "🛰️ Cockpit · IDocs & queues", impact: "💸 Impact in $ · live", impactNow: "Money stuck right now", impactRows: [["Billing (e-invoice stuck)", "$ 52.0k"], ["Orders blocked (CPI)", "$ 24.7k"], ["Tax at risk (DRC)", "$ 12.5k"]], note: "Representative screens of the product UI.", tryTitle: "Try the AI now — no signup", trySub: "A sample CPI failure. Click and see the diagnosis + fix.", healthAvg: "avg health", cockpitApproval: "✓ Remediation with approval · production lock", impactTotal: "$ 89.2k" },
    demo: { fail: "❌ CPI · B2B Orders — FAILED", btn: "🤖 Diagnose", btnRunning: "Diagnosing…", hint: "Click “Diagnose” and watch the AI find the root cause and the fix — no signup.", script: ["🔎 Reading the Message Processing Log of iFlow ‘B2B Orders’…", "⚠️ Root cause: Sold-to party 0001234 does not exist in S/4HANA.", "🛠️ Fix: create/check the BP (XD01/BP) and reprocess the message.", "📋 Likely SAP Note: 2900000 — Sales Order replication error.", "✅ Fix ready to apply (with approval · production lock)."] },
    roi: { badge: "CALCULATOR", title: "How much does a stuck integration cost you?", sub: "Adjust with your numbers and see the estimated savings — the language the CFO understands.", hoursLabel: "Unplanned downtime hours / month (portfolio)", costLabel: "Average cost of downtime per hour", assume: "Estimate: fast detection and remediation cut downtime by up to 70%. Adjust with your numbers.", loseNow: "You lose today, per month", saved: "Estimated savings with SAPLINK", perMonth: "/mo", perYear: "/yr", cta: "I want to recover this →" },
    problema: { title: "Being reactive costs clients and margin", p: "SAP integrations break silently and the client finds out before you do. The team firefights, with no single view, and proving the value delivered is hard. SAPLINK flips the game.", cards: [["Before", "Stuck IDoc, RFC down, e-invoice halted — found out too late."], ["Without SAPLINK", "Spreadsheets, transaction by transaction, client by client. Doesn't scale."], ["With SAPLINK", "One radar, alerts, AI and value proof in $. You're in control."]], beforeTag: "BEFORE · reactive", beforeText: "Spreadsheets, transaction by transaction, client by client. Stuck IDoc found late. Client calls before you notice.", beforeChips: ["no single view", "firefighting", "invisible value"], afterTag: "AFTER · with SAPLINK", afterText: "One portfolio radar · prioritized alerts · AI diagnoses and fixes · $ at risk live · SLA per client.", afterChips: ["health 92", "0 open ports", "−70% downtime", "proof in $"], drag: "← drag to compare →" },
    como: { title: "How it works", sub: "From the client's SAP to action — data flows outbound only, no open ports.", flow: [["🗄️", "Client's SAP", "S/4 · ECC · CPI"], ["🔌", "Agent / Connector", "outbound-only · OData"], ["◆", "SAPLINK", "AI · multi-client"], ["✅", "Action & value", "alert · fix · $"]], steps: [["1", "Connect", "Docker Agent (RFC/IDoc) with outbound HTTPS only, or Communication Arrangement on S/4HANA Cloud. Zero open ports."], ["2", "See", "Health of every integration across every client in one multi-client dashboard, in real time."], ["3", "Anticipate & fix", "AI diagnoses, predicts failures and remediates (with approval) — IDoc, queue, RFC, tax."], ["4", "Prove value", "SLA per client, impact in $ and a white-label portal. You become the client's SAP radar."]] },
    plataforma: { title: "One platform, everything SAP operations needs", sub: "20+ capabilities — from the classic cockpit to AI and S/4HANA Cloud." },
    groups: [
      { accent: "#22d3ee", title: "Operations", feats: [
        { key: "Cockpit de IDoc & filas", icon: "🛰️", name: "IDoc & queue cockpit", tagline: "BD87 + SMQ + SM58 in one multi-client panel" },
        { key: "Remediação autônoma", icon: "✨", name: "Autonomous remediation", tagline: "Reprocess/unblock with approval and log" },
        { key: "Catálogo de interfaces", icon: "📚", name: "Interface catalog", tagline: "Auto-discovered landscape (WE20/SM59)" },
        { key: "Alertas em tempo real", icon: "🔔", name: "Real-time alerts", tagline: "Automatic detection and resolution" } ] },
      { accent: "#a78bfa", title: "AI Intelligence", feats: [
        { key: "Copiloto da carteira", icon: "💬", name: "Portfolio copilot", tagline: "Ask in natural language" },
        { key: "Diagnóstico + SAP Notes", icon: "🤖", name: "Diagnosis + SAP Notes", tagline: "Root cause and the likely Note" },
        { key: "Previsão de falha", icon: "🔮", name: "Failure prediction", tagline: "Anomaly before it breaks" },
        { key: "Digest semanal por IA", icon: "📬", name: "Weekly AI digest", tagline: "White-label summary by email" } ] },
      { accent: "#34d399", title: "Value & SLA", feats: [
        { key: "SLA por cliente", icon: "📈", name: "SLA per client", tagline: "Compliance + AI report" },
        { key: "Impacto em R$", icon: "💰", name: "Impact in $", tagline: "Cost of downtime per hour" },
        { key: "Benchmark de mercado", icon: "🏆", name: "Market benchmark", tagline: "Your portfolio vs percentile" },
        { key: "Portal do cliente", icon: "🪪", name: "Client portal", tagline: "White-label, read-only" } ] },
      { accent: "#fbbf24", title: "S/4HANA Cloud", feats: [
        { key: "Radar de Upgrade", icon: "🚀", name: "Upgrade Radar", tagline: "What breaks in the next release" },
        { key: "Clean Core Score", icon: "🧼", name: "Clean Core Score", tagline: "The metric SAP demands" },
        { key: "Fiscal DRC (NF-e)", icon: "🧾", name: "Tax DRC (e-invoice)", tagline: "Tax authority rejection, contingency" },
        { key: "Event Mesh + CPI/AIF", icon: "📨", name: "Event Mesh + CPI/AIF", tagline: "Dead-letter, lag, MPL" } ] },
      { accent: "#f87171", title: "Response & Trust", feats: [
        { key: "On-call multicanal", icon: "📣", name: "Multichannel on-call", tagline: "Slack/Teams/Webhook/email + escalation" },
        { key: "Tickets Jira/ServiceNow", icon: "🎫", name: "Jira/ServiceNow tickets", tagline: "Alert becomes a ticket and closes itself" },
        { key: "Radar de validade", icon: "📡", name: "Validity radar", tagline: "Certificates and secrets expiring" },
        { key: "Transports (STMS)", icon: "🚚", name: "Transports (STMS)", tagline: "Correlates incident vs transport" } ] },
    ],
    featHover: "See details, simulator and how to implement →",
    s4: { badge: "FLAGSHIP", titlePre: "Ready for", sub: "The edition SAP is pushing on everyone — no GUI, forced upgrade 2×/year and API-first. SAPLINK covers exactly what's missing, connecting via Communication Arrangement (OAuth), with nothing installed.", cards: [
      { icon: "🚀", title: "Upgrade Radar", desc: "What will break in the next release — mapped to what you actually use." },
      { icon: "🧼", title: "Clean Core Score", desc: "The metric SAP itself demands, with a remediation plan." },
      { icon: "🧾", title: "Tax DRC", desc: "E-invoice / tax authority: rejection, contingency and reprocessing. Wins the BR market." },
      { icon: "📨", title: "Event Mesh + CPI/AIF", desc: "Real dead-letter, lag and Message Processing Logs." } ] },
    innovHead: { badge: "🦄 EXCLUSIVE · LIVE", title: "What no other system has", sub: "Thirteen differentiators that become a moat: network effect, cross-layer data only we have, autonomy, reconciliation, AI that writes the fix, operating via WhatsApp, change preflight, time machine, audit, FinOps and the CFO's language. Click to explore with a simulator.", hover: "Open details + simulator →", more: "See all features in detail, with examples and gains →" },
    innovations: [
      { key: "Rede Federada de Falhas", icon: "🛰️", name: "Federated Failure Network", tagline: "The \"Waze of SAP\"", desc: "Every failure and the fix that worked become anonymous network knowledge. When something breaks at your client, SAPLINK already knows the winning fix — because it saw it happen across dozens of other environments.", benefit: "Gets smarter with every client (network effect)." },
      { key: "Causa raiz cross-camada", icon: "🔗", name: "Cross-layer root cause", tagline: "On-prem + cloud together", desc: "Cross-references transports (STMS) with the CPI/IDoc failures that followed and points to the change that likely caused them. No one else has both layers in one place.", benefit: "Find the cause in minutes, not hours." },
      { key: "AMS Autônomo", icon: "🤖", name: "Autonomous AMS", tagline: "Self-healing that learns", desc: "Detect → diagnose → fix → measure → learn. High-confidence fixes are applied on their own (with rollback and trail). Confidence comes from the Federated Network.", benefit: "Cuts manual L1/L2 to nearly zero." },
      { key: "Dinheiro em risco (ao vivo)", icon: "💸", name: "Money at risk (live)", tagline: "CFO language", desc: "Translates each technical failure into money stuck now — cost of downtime per hour + blocked tax documents, per business process.", benefit: "Shifts the sales talk from technical to financial." },
      { key: "Reconciliação ponta-a-ponta", icon: "🔁", name: "End-to-end reconciliation", tagline: "Delivered ≠ became business", desc: "Tracks the document through its journey (order → sales order → invoice) and shows where volume is lost. Catches the silent failure that says \"success\" but the object was never created.", benefit: "Finds the leak no monitor sees." },
      { key: "Remediação generativa", icon: "⚙️", name: "Generative remediation", tagline: "The AI writes the fix", desc: "It doesn't just describe the problem — it delivers the ready artifact (Groovy, mapping, OData filter) to paste and apply.", benefit: "From \"explains\" to \"solves\" in seconds." },
      { key: "ChatOps por WhatsApp", icon: "💬", name: "ChatOps via WhatsApp", tagline: "Operate SAP by message", desc: "\"Reprocess client X's IDocs\" via WhatsApp/Telegram — the AI understands, acts and asks for approval on anything that touches SAP.", benefit: "Operations in your hand, no panel needed." },
      { key: "Perda silenciosa de negócio", icon: "📉", name: "Silent business loss", tagline: "Revenue radar", desc: "Alerts when volume drops well below normal — even with everything technically green. Catches revenue stalling before it becomes a complaint.", benefit: "Sees the loss the technical monitor can't." },
      { key: "Pré-voo de mudança", icon: "🧨", name: "Change preflight", tagline: "Blast radius before deploy", desc: "Before the transport goes to PRD, it shows the blast radius (interfaces, processes, $) and the risk score — with a test plan.", benefit: "Ends the post-upgrade surprise." },
      { key: "Time machine de incidente", icon: "⏪", name: "Incident time machine", tagline: "Replay + 'what if?'", desc: "Reconstructs the incident timeline and shows how much would have been saved with faster detection.", benefit: "Irrefutable ROI proof." },
      { key: "Auditoria & Compliance", icon: "🛡️", name: "Audit & Compliance", tagline: "Automatic SoD", desc: "Trail of changes and remediations + segregation-of-duties check, with evidence ready for the auditor.", benefit: "Compliance without building a spreadsheet." },
      { key: "Parceiros EDI", icon: "🤝", name: "EDI partners", tagline: "Who sends bad data", desc: "Ranks partners by error frequency — so you charge the right supplier, not your own IT.", benefit: "Ammunition to charge the partner." },
      { key: "FinOps de BTP", icon: "💵", name: "BTP FinOps", tagline: "Cloud cost per IFlow", desc: "Links volume to BTP consumption and flags the runaway IFlow burning credit.", benefit: "No more surprise on the BTP bill." },
    ],
    comparativo: { title: "Why SAPLINK and not the rest", sub: "Competitors cover a slice. SAPLINK covers the whole — with AI and value proof.", cols: ["Spreadsheet / manual", "Generic monitor", "SAP Focused Run", "SAPLINK"], rows: [["Multi-client in one dashboard", "✗", "~", "~", "✓"], ["IDoc/RFC + CPI + S/4HANA Cloud together", "✗", "~", "~", "✓"], ["AI: diagnosis + ready-made fix", "✗", "✗", "~", "✓"], ["Remediation with approval + PRD lock", "✗", "✗", "~", "✓"], ["Value proof in $ / SLA per client", "~", "✗", "~", "✓"], ["BR tax (e-invoice, SPED, eSocial)", "✗", "✗", "✗", "✓"], ["No open ports / no S-user", "✓", "~", "✗", "✓"], ["White-label + client portal", "✗", "✗", "✗", "✓"], ["Live in days", "✓", "~", "✗", "✓"]], legend: "✓ yes · ~ partial · ✗ no" },
    trust: { title: "Safe for your client's environment", band: [["🔒", "No inbound ports on the client"], ["🪪", "No S-user · no add-on"], ["🔑", "Encrypted credentials (AES)"], ["🧱", "Multi-tenant isolation"], ["✋", "SAP changes only with approval"], ["🌎", "LGPD compliant"], ["🟢", "Production lock (PRD)"], ["🧪", "DEV/HML/PRD environments"]], cards: [["🇧🇷 Data in Brazil", "Hosting and data under LGPD; you are the controller, SAPLINK is the processor."], ["🔐 Least privilege", "Connects via released APIs / Communication Arrangement. No S-user, no add-on, no inbound port."], ["✋ SAP changes need approval", "Every remediation is approve→execute→log. In production, extra confirmation (PRD lock)."]], roadmap: "SOC 2 / ISO 27001 certifications on the roadmap." },
    planos: { title: "Pricing", sub1: "Extra integration and user add-ons. Auto-billing or one-off.", sub2: "🎁 1st month free on Business and Enterprise · Pro with 50% OFF the 1st month · 3-month minimum.", monthly: "Monthly", annual: "Annual", annualBadge: "2 months free", perYear: "/yr", perMonthEq: "/mo · 2 months free", cta: "I'm interested" },
    faq: { title: "Frequently asked questions", items: [["Do I need to open ports on the client's SAP?", "No. OData/REST is monitored directly; RFC/IDoc uses the Docker Agent with outbound-only traffic. On S/4HANA Cloud it connects via Communication Arrangement (OAuth) — nothing installed on the client."], ["Does it work with S/4HANA Cloud?", "Yes — it's our flagship: Upgrade Radar, Clean Core Score, Tax (DRC), Event Mesh and CPI/AIF, via released APIs."], ["Is the data secure?", "Credentials encrypted at rest, multi-tenant isolation per consultancy, and no SAP action runs without human approval (with log)."], ["Is it white-label?", "Yes. Your consultancy's logo and color in the UI, reports and the end-client portal."], ["Does it separate DEV, QA and production?", "Yes. Each integration has an environment (DEV/HML/PRD); data, connections, metrics and billing are isolated. In production there's an extra lock: remediation and auto-heal require human approval."], ["How long to deploy?", "Days, not months. Connect via Communication Arrangement (cloud) or the Docker Agent (on-prem) and data starts showing up."], ["What about data privacy?", "LGPD compliant: encrypted data, isolation per consultancy, and published Terms + Policy. You are the controller; SAPLINK is the processor."], ["Is there a commitment?", "3-month minimum. 1st month free on Business/Enterprise and 50% OFF the 1st month on Pro."], ["How do I sell it from my consultancy?", "As a monthly monitoring and governance service per client — recurring revenue, retention and value proof in $."]] },
    lead: { tag: "Free material", title: "SAPLINK sales deck (PDF)", sub: "The full picture to present internally or to the client: what it monitors, how it drives recurring revenue and value proof in $.", placeholder: "you@email.com", btn: "Get the material", btnSending: "Unlocking…", doneMsg: "✓ Done! Your material is unlocked.", download: "⬇ Download the deck (PDF)" },
    ctaFinal: { title: "Stop firefighting. Start operating.", sub: "Leave your contact — the sales team shows SAPLINK on your clients' SAP.", btn: "I'm interested →" },
    footer: { tagline: "SAP integration operations", terms: "Terms", privacy: "Privacy", contract: "Contract/SLA", contact: "Contact", login: "Sign in" },
    interest: { title: "I'm interested", sub: "Leave your details and the sales team will reach out.", name: "Name *", email: "Email *", phone: "Phone / WhatsApp", company: "Company / Consultancy", role: "Your role", message: "What are you looking for? (optional)", send: "Send", sending: "Sending…", okTitle: "We got your interest!", okMsg: "Our team will reach out soon. Thank you!", close: "Close", err: "Couldn't send. Please try again." },
  },
  es: {
    nav: [{ id: "problema", label: "Problema" }, { id: "cobertura", label: "Cobertura" }, { id: "produto", label: "Por dentro" }, { id: "roi", label: "ROI" }, { id: "comparativo", label: "Comparativa" }, { id: "planos", label: "Planes" }, { id: "faq", label: "FAQ" }],
    hero: { badge: "18+ productos SAP · IA de punta a punta · white-label", titleA: "Moderniza la operación", titleB: "de tu consultora", rotate: ["S/4HANA Cloud", "Ariba & SF", "CPI & AIF", "BTP", "fiscal BR", "todo el SAP"], subtitle: "Un solo panel que monitorea, anticipa, corrige y prueba valor en $ en todo el landscape SAP del cliente — del IDoc clásico al S/4HANA Cloud, Ariba, SuccessFactors, BTP y fiscal brasileño.", ctaPrimary: "Quiero modernizar mi operación →", ctaSecondary: "Ver todo lo que cubrimos", micro: ["✓ Sin abrir puertos en el cliente", "✓ Multicliente", "✓ Listo en días, no meses"], live: { title: "SAPLINK · cartera en vivo", health: "Salud de la cartera", risk: "En riesgo ahora", cur: "$", feed: ["La IA corrigió 3 IDocs trabados · sin intervención", "Alerta CRITICAL en CPI · diagnóstico en 4s", "Factura rechazada reprocesada · OK", "Cola qRFC desbloqueada · 0 pendientes", "Runbook aplicado · 'Sold-to not found'"], rows: ["S/4HANA Cloud · OData", "CPI · Pedidos B2B", "IDoc · INVOIC02", "RFC · PI_PROD", "Event Mesh · BP"] } },
    metrics: [["18+", "productos SAP cubiertos"], ["20+", "capacidades en la plataforma"], ["13", "diferenciales que nadie tiene"], ["0", "puertos abiertos en el cliente"]],
    feitoPara: "Hecho para",
    personas: [["🏢", "Consultoras SAP", "Monitorea toda la cartera de clientes en un panel, con tu marca."], ["🛠️", "Equipos de AMS / Soporte", "Menos apagar incendios: detección, diagnóstico y remediación con aprobación."], ["🤝", "Socios e Integradores", "Prueba valor en $ al cliente y aumenta retención e ingresos recurrentes."]],
    coverage: { badge: "COBERTURA TOTAL", title: "Todo el universo SAP de tu cliente. En una pantalla.", sub: "Integración clásica, nube, LoB, plataforma, Basis y fiscal brasileño — el competidor cubre un trozo; SAPLINK cubre el conjunto.", items: cov(COV_SUB_ES) },
    produto: { badge: "POR DENTRO", title: "Mira SAPLINK por dentro", sub: "Paneles reales del producto — salud de la cartera, cockpit operativo y el impacto en $.", dash: "📊 Dashboard · salud de la cartera", cockpit: "🛰️ Cockpit · IDocs y colas", impact: "💸 Impacto en $ · en vivo", impactNow: "Dinero detenido ahora", impactRows: [["Facturación (factura detenida)", "$ 52,0k"], ["Pedidos trabados (CPI)", "$ 24,7k"], ["Fiscal en riesgo (DRC)", "$ 12,5k"]], note: "Pantallas representativas de la interfaz del producto.", tryTitle: "Prueba la IA ahora — sin registro", trySub: "Una falla de CPI de ejemplo. Haz clic y mira el diagnóstico + corrección.", healthAvg: "salud media", cockpitApproval: "✓ Remediación con aprobación · bloqueo de producción", impactTotal: "$ 89,2k" },
    demo: { fail: "❌ CPI · Pedidos B2B — FALLA", btn: "🤖 Diagnosticar", btnRunning: "Diagnosticando…", hint: "Haz clic en “Diagnosticar” y mira a la IA encontrar la causa raíz y la corrección — sin registro.", script: ["🔎 Leyendo el Message Processing Log del iFlow ‘Pedidos B2B’…", "⚠️ Causa raíz: Sold-to party 0001234 no existe en S/4HANA.", "🛠️ Corrección: crear/verificar el BP (XD01/BP) y reprocesar el mensaje.", "📋 SAP Note probable: 2900000 — Sales Order replication error.", "✅ Corrección lista para aplicar (con aprobación · bloqueo de producción)."] },
    roi: { badge: "CALCULADORA", title: "¿Cuánto te cuesta una integración detenida?", sub: "Ajusta con tus números y mira el ahorro estimado — el lenguaje que entiende el CFO.", hoursLabel: "Horas de parada no planificada / mes (cartera)", costLabel: "Costo medio de parada por hora", assume: "Estimación: detección y remediación rápidas reducen hasta 70% del tiempo de parada. Ajusta con tus números.", loseNow: "Pierdes hoy, por mes", saved: "Ahorro estimado con SAPLINK", perMonth: "/mes", perYear: "/año", cta: "Quiero recuperar ese valor →" },
    problema: { title: "Ser reactivo cuesta clientes y margen", p: "La integración SAP se rompe en silencio y el cliente se entera antes que tú. El equipo apaga incendios, sin visión única, y probar el valor entregado es difícil. SAPLINK da vuelta el juego.", cards: [["Antes", "IDoc trabado, RFC caída, factura detenida — descubierto demasiado tarde."], ["Sin SAPLINK", "Planilla, transacción por transacción, cliente por cliente. No escala."], ["Con SAPLINK", "Un radar, alertas, IA y prueba de valor en $. Tú al control."]], beforeTag: "ANTES · reactivo", beforeText: "Planilla, transacción por transacción, cliente por cliente. IDoc trabado descubierto tarde. El cliente llama antes de que lo veas.", beforeChips: ["sin visión única", "apaga incendios", "valor invisible"], afterTag: "DESPUÉS · con SAPLINK", afterText: "Un radar de la cartera · alertas priorizadas · la IA diagnostica y corrige · $ en riesgo en vivo · SLA por cliente.", afterChips: ["salud 92", "0 puertos abiertos", "−70% downtime", "prueba en $"], drag: "← arrastra para comparar →" },
    como: { title: "Cómo funciona", sub: "Del SAP del cliente a la acción — el dato fluye solo de salida, sin abrir puertos.", flow: [["🗄️", "SAP del cliente", "S/4 · ECC · CPI"], ["🔌", "Agente / Conector", "solo salida · OData"], ["◆", "SAPLINK", "IA · multicliente"], ["✅", "Acción y valor", "alerta · corrección · $"]], steps: [["1", "Conecta", "Agente Docker (RFC/IDoc) solo con salida HTTPS, o Communication Arrangement en S/4HANA Cloud. Cero puertos abiertos."], ["2", "Observa", "Salud de todas las integraciones de todos los clientes en un panel multicliente, en tiempo real."], ["3", "Anticipa y corrige", "La IA diagnostica, anticipa fallas y remedia (con aprobación) — IDoc, cola, RFC, fiscal."], ["4", "Prueba valor", "SLA por cliente, impacto en $ y portal white-label. Te conviertes en el radar SAP del cliente."]] },
    plataforma: { title: "Una plataforma, todo lo que la operación SAP necesita", sub: "Más de 20 capacidades — del cockpit clásico a la IA y al S/4HANA Cloud." },
    groups: [
      { accent: "#22d3ee", title: "Operación", feats: [
        { key: "Cockpit de IDoc & filas", icon: "🛰️", name: "Cockpit de IDoc y colas", tagline: "BD87 + SMQ + SM58 en un panel multicliente" },
        { key: "Remediação autônoma", icon: "✨", name: "Remediación autónoma", tagline: "Reprocesa/desbloquea con aprobación y log" },
        { key: "Catálogo de interfaces", icon: "📚", name: "Catálogo de interfaces", tagline: "Landscape auto-descubierto (WE20/SM59)" },
        { key: "Alertas em tempo real", icon: "🔔", name: "Alertas en tiempo real", tagline: "Detección y resolución automática" } ] },
      { accent: "#a78bfa", title: "Inteligencia IA", feats: [
        { key: "Copiloto da carteira", icon: "💬", name: "Copiloto de la cartera", tagline: "Pregunta en lenguaje natural" },
        { key: "Diagnóstico + SAP Notes", icon: "🤖", name: "Diagnóstico + SAP Notes", tagline: "Causa raíz y la Nota probable" },
        { key: "Previsão de falha", icon: "🔮", name: "Predicción de fallas", tagline: "Anomalía antes de romper" },
        { key: "Digest semanal por IA", icon: "📬", name: "Digest semanal por IA", tagline: "Resumen white-label por email" } ] },
      { accent: "#34d399", title: "Valor y SLA", feats: [
        { key: "SLA por cliente", icon: "📈", name: "SLA por cliente", tagline: "Compliance + informe por IA" },
        { key: "Impacto em R$", icon: "💰", name: "Impacto en $", tagline: "Costo de la parada por hora" },
        { key: "Benchmark de mercado", icon: "🏆", name: "Benchmark de mercado", tagline: "Tu cartera vs percentil" },
        { key: "Portal do cliente", icon: "🪪", name: "Portal del cliente", tagline: "White-label, solo lectura" } ] },
      { accent: "#fbbf24", title: "S/4HANA Cloud", feats: [
        { key: "Radar de Upgrade", icon: "🚀", name: "Radar de Upgrade", tagline: "Lo que rompe en el próximo release" },
        { key: "Clean Core Score", icon: "🧼", name: "Clean Core Score", tagline: "La métrica que SAP exige" },
        { key: "Fiscal DRC (NF-e)", icon: "🧾", name: "Fiscal DRC (factura)", tagline: "Rechazo del fisco, contingencia" },
        { key: "Event Mesh + CPI/AIF", icon: "📨", name: "Event Mesh + CPI/AIF", tagline: "Dead-letter, lag, MPL" } ] },
      { accent: "#f87171", title: "Respuesta y Confianza", feats: [
        { key: "On-call multicanal", icon: "📣", name: "On-call multicanal", tagline: "Slack/Teams/Webhook/email + escalamiento" },
        { key: "Tickets Jira/ServiceNow", icon: "🎫", name: "Tickets Jira/ServiceNow", tagline: "La alerta se vuelve ticket y se cierra sola" },
        { key: "Radar de validade", icon: "📡", name: "Radar de validez", tagline: "Certificados y secretos por vencer" },
        { key: "Transports (STMS)", icon: "🚚", name: "Transports (STMS)", tagline: "Correlaciona incidente vs transport" } ] },
    ],
    featHover: "Ver detalles, simulador y cómo implementar →",
    s4: { badge: "PRODUCTO ESTRELLA", titlePre: "Listo para el", sub: "La edición que SAP empuja a todos — sin GUI, upgrade forzado 2×/año y API-first. SAPLINK cubre exactamente lo que falta, conectando por Communication Arrangement (OAuth), sin instalar nada.", cards: [
      { icon: "🚀", title: "Radar de Upgrade", desc: "Lo que va a romper en el próximo release — mapeado a lo que usas." },
      { icon: "🧼", title: "Clean Core Score", desc: "La métrica que la propia SAP exige, con plan de remediación." },
      { icon: "🧾", title: "Fiscal DRC", desc: "Factura electrónica / fisco: rechazo, contingencia y reproceso. Gana el mercado BR." },
      { icon: "📨", title: "Event Mesh + CPI/AIF", desc: "Dead-letter, lag y Message Processing Logs reales." } ] },
    innovHead: { badge: "🦄 EXCLUSIVO · EN VIVO", title: "Lo que no existe en ningún otro sistema", sub: "Trece diferenciales que se vuelven moat: efecto de red, dato cross-capa que solo nosotros tenemos, autonomía, reconciliación, IA que escribe la corrección, operación por WhatsApp, pre-vuelo de cambio, time machine, auditoría, FinOps y el lenguaje del CFO. Haz clic para explorar con simulador.", hover: "Abrir detalles + simulador →", more: "Ver todas las funcionalidades en detalle, con ejemplos y ganancias →" },
    innovations: [
      { key: "Rede Federada de Falhas", icon: "🛰️", name: "Red Federada de Fallas", tagline: "El \"Waze del SAP\"", desc: "Cada falla y la corrección que funcionó se vuelven conocimiento anónimo de la red. Cuando algo rompe en tu cliente, SAPLINK ya sabe la corrección ganadora — porque la vio ocurrir en decenas de otros entornos.", benefit: "Se vuelve más inteligente con cada cliente (efecto de red)." },
      { key: "Causa raiz cross-camada", icon: "🔗", name: "Causa raíz cross-capa", tagline: "On-prem + nube juntos", desc: "Cruza los transports (STMS) con las fallas de CPI/IDoc que vinieron después y señala el cambio que probablemente las causó. Nadie más tiene las dos capas en el mismo lugar.", benefit: "Encontrar la causa en minutos, no en horas." },
      { key: "AMS Autônomo", icon: "🤖", name: "AMS Autónomo", tagline: "Self-healing que aprende", desc: "Detecta → diagnostica → corrige → mide → aprende. Las correcciones de alta confianza se aplican solas (con rollback y rastro). La confianza viene de la Red Federada.", benefit: "Reduce el L1/L2 manual a casi cero." },
      { key: "Dinheiro em risco (ao vivo)", icon: "💸", name: "Dinero en riesgo (en vivo)", tagline: "Lenguaje de CFO", desc: "Traduce cada falla técnica en dinero detenido ahora — costo de parada por hora + documentos fiscales bloqueados, por proceso de negocio.", benefit: "Cambia la conversación de venta de técnica a financiera." },
      { key: "Reconciliação ponta-a-ponta", icon: "🔁", name: "Reconciliación de punta a punta", tagline: "Entregado ≠ se volvió negocio", desc: "Rastrea el documento por su jornada (pedido → orden → factura) y muestra dónde se pierde el volumen. Atrapa la falla silenciosa que dice \"éxito\" pero el objeto nunca nació.", benefit: "Encuentra la fuga que ningún monitor ve." },
      { key: "Remediação generativa", icon: "⚙️", name: "Remediación generativa", tagline: "La IA escribe la corrección", desc: "No solo describe el problema — entrega el artefacto listo (Groovy, mapeo, filtro OData) para pegar y aplicar.", benefit: "De \"explica\" a \"resuelve\" en segundos." },
      { key: "ChatOps por WhatsApp", icon: "💬", name: "ChatOps por WhatsApp", tagline: "Opera SAP por mensaje", desc: "\"Reprocesa los IDocs del cliente X\" por WhatsApp/Telegram — la IA entiende, actúa y pide aprobación para lo que toca el SAP.", benefit: "Operación en la palma de la mano, sin abrir el panel." },
      { key: "Perda silenciosa de negócio", icon: "📉", name: "Pérdida silenciosa de negocio", tagline: "Radar de ingresos", desc: "Alerta cuando el volumen cae muy por debajo de lo normal — incluso con todo verde técnicamente. Captura los ingresos deteniéndose antes de volverse un reclamo.", benefit: "Ve la pérdida que el monitor técnico no ve." },
      { key: "Pré-voo de mudança", icon: "🧨", name: "Pre-vuelo de cambio", tagline: "Blast radius antes del deploy", desc: "Antes de que el transport vaya a PRD, muestra el radio de impacto (interfaces, procesos, $) y el score de riesgo — con plan de prueba.", benefit: "Acaba con la sorpresa post-upgrade." },
      { key: "Time machine de incidente", icon: "⏪", name: "Time machine de incidente", tagline: "Replay + '¿y si?'", desc: "Reconstruye la línea de tiempo del incidente y muestra cuánto se habría ahorrado con detección más rápida.", benefit: "Prueba de ROI irrefutable." },
      { key: "Auditoria & Compliance", icon: "🛡️", name: "Auditoría & Compliance", tagline: "SoD automático", desc: "Rastro de cambios y remediaciones + chequeo de segregación de funciones, con evidencias listas para el auditor.", benefit: "Compliance sin armar una planilla." },
      { key: "Parceiros EDI", icon: "🤝", name: "Socios EDI", tagline: "Quién manda datos malos", desc: "Rankea socios por frecuencia de error — para cobrarle al proveedor correcto, no a tu TI.", benefit: "Munición para cobrarle al socio." },
      { key: "FinOps de BTP", icon: "💵", name: "FinOps de BTP", tagline: "Costo de nube por IFlow", desc: "Liga el volumen al consumo de BTP y marca el IFlow descontrolado quemando crédito.", benefit: "Fin de la sorpresa en la factura de BTP." },
    ],
    comparativo: { title: "Por qué SAPLINK y no el resto", sub: "El competidor cubre un trozo. SAPLINK cubre el conjunto — con IA y prueba de valor.", cols: ["Planilla / manual", "Monitor genérico", "SAP Focused Run", "SAPLINK"], rows: [["Multicliente en un panel", "✗", "~", "~", "✓"], ["IDoc/RFC + CPI + S/4HANA Cloud juntos", "✗", "~", "~", "✓"], ["IA: diagnóstico + corrección lista", "✗", "✗", "~", "✓"], ["Remediación con aprobación + bloqueo PRD", "✗", "✗", "~", "✓"], ["Prueba de valor en $ / SLA por cliente", "~", "✗", "~", "✓"], ["Fiscal BR (factura, SPED, eSocial)", "✗", "✗", "✗", "✓"], ["Sin abrir puertos / sin S-user", "✓", "~", "✗", "✓"], ["White-label + portal del cliente", "✗", "✗", "✗", "✓"], ["Listo en días", "✓", "~", "✗", "✓"]], legend: "✓ sí · ~ parcial · ✗ no" },
    trust: { title: "Seguro para el entorno de tu cliente", band: [["🔒", "Sin puertos abiertos en el cliente"], ["🪪", "Sin S-user · sin add-on"], ["🔑", "Credenciales cifradas (AES)"], ["🧱", "Aislamiento multi-tenant"], ["✋", "Cambios en SAP solo con aprobación"], ["🌎", "Conforme a LGPD"], ["🟢", "Bloqueo de producción (PRD)"], ["🧪", "Entornos DEV/HML/PRD"]], cards: [["🇧🇷 Datos en Brasil", "Hosting y datos bajo LGPD; tú eres el controlador, SAPLINK el operador."], ["🔐 Acceso mínimo", "Conexión por APIs liberadas / Communication Arrangement. Sin S-user, sin add-on, sin puerto de entrada."], ["✋ Cambios en SAP con aprobación", "Toda remediación es aprobar→ejecutar→log. En producción, confirmación extra (bloqueo PRD)."]], roadmap: "Certificaciones SOC 2 / ISO 27001 en el roadmap." },
    planos: { title: "Planes", sub1: "Add-ons de integración y usuario extra. Cobro automático o puntual.", sub2: "🎁 1er mes gratis en Business y Enterprise · Pro con 50% OFF el 1er mes · permanencia mínima de 3 meses.", monthly: "Mensual", annual: "Anual", annualBadge: "2 meses gratis", perYear: "/año", perMonthEq: "/mes · 2 meses gratis", cta: "Me interesa" },
    faq: { title: "Preguntas frecuentes", items: [["¿Necesito abrir puertos en el SAP del cliente?", "No. OData/REST se monitorea directo; RFC/IDoc usa el Agente Docker con tráfico solo de salida. En S/4HANA Cloud conecta por Communication Arrangement (OAuth) — nada instalado en el cliente."], ["¿Funciona con S/4HANA Cloud?", "Sí — es nuestro producto estrella: Upgrade Radar, Clean Core Score, Fiscal (DRC), Event Mesh y CPI/AIF, vía APIs liberadas."], ["¿Los datos están seguros?", "Credenciales cifradas en reposo, aislamiento multi-tenant por consultora, y ninguna acción en SAP corre sin aprobación humana (con log)."], ["¿Es white-label?", "Sí. Logo y color de tu consultora en la interfaz, los informes y el portal del cliente final."], ["¿Separa DEV, homologación y producción?", "Sí. Cada integración tiene entorno (DEV/HML/PRD); datos, conexiones, métricas y facturación quedan aislados. En producción hay bloqueo extra: remediación y auto-heal requieren aprobación humana."], ["¿Cuánto tarda la implantación?", "Días, no meses. Conecta por Communication Arrangement (nube) o el Agente Docker (on-prem) y los datos empiezan a aparecer."], ["¿Y la privacidad de datos?", "Conforme a LGPD: datos cifrados, aislamiento por consultora, y Términos + Política publicados. Tú eres el controlador; SAPLINK el operador."], ["¿Hay permanencia?", "Permanencia mínima de 3 meses. 1er mes gratis en Business/Enterprise y 50% OFF el 1er mes en Pro."], ["¿Cómo lo vendo desde mi consultora?", "Como servicio mensual de monitoreo y gobernanza por cliente — ingresos recurrentes, retención y prueba de valor en $."]] },
    lead: { tag: "Material gratuito", title: "Deck de ventas de SAPLINK (PDF)", sub: "La visión completa para presentar internamente o al cliente: qué monitorea, cómo genera ingresos recurrentes y prueba de valor en $.", placeholder: "tu@email.com", btn: "Recibir el material", btnSending: "Liberando…", doneMsg: "✓ ¡Listo! Tu material está liberado.", download: "⬇ Descargar el deck (PDF)" },
    ctaFinal: { title: "Deja de apagar incendios. Empieza a operar.", sub: "Deja tu contacto — el equipo de ventas te muestra SAPLINK en el SAP de tus clientes.", btn: "Me interesa →" },
    footer: { tagline: "Operación de integraciones SAP", terms: "Términos", privacy: "Privacidad", contract: "Contrato/SLA", contact: "Contacto", login: "Entrar" },
    interest: { title: "Me interesa", sub: "Deja tus datos y el equipo de ventas te contactará.", name: "Nombre *", email: "Email *", phone: "Teléfono / WhatsApp", company: "Empresa / Consultora", role: "Tu cargo", message: "¿Qué buscas? (opcional)", send: "Enviar", sending: "Enviando…", okTitle: "¡Recibimos tu interés!", okMsg: "Nuestro equipo te contactará pronto. ¡Gracias!", close: "Cerrar", err: "No se pudo enviar. Inténtalo de nuevo." },
  },
};
